on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/cnppromo-server/htdocs/server.cnppromo.com
            git pull

            # Ensure Node.js is installed
            if ! command -v node &> /dev/null; then
              echo "Installing Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Ensure npm is available
            export PATH=$PATH:/usr/local/bin
            source ~/.bashrc

            # Recheck Node.js installation
            node -v
            npm -v

            # Install pnpm globally
            if ! command -v pnpm &> /dev/null; then
              echo "Installing pnpm..."
              npm install -g pnpm
            fi

            # Install PM2 globally
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              npm install -g pm2
            fi

            # Install dependencies and restart the application
            pnpm install
            pm2 restart 0 --update-env